import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./nav/Navbar";
import ToastarProvider from "./providers/ToastarProvider";
import SignalRProvider from "./providers/SignalRProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
   template:  "%s - Mazad",
   default:"Mazad"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={geistSans.variable}>
      <body className={`${geistSans.className}`} >
        <Navbar/>
        <main className="container mx-auto px-5 pt-10 mb-10">
          <SignalRProvider>

        {children}
          </SignalRProvider>
        </main>
        <ToastarProvider/>
      </body>
    </html>
  );
}
